### ISSUE TITLE
How to include and estimate RDD model with covariate(s)

### ISSUE THREAD

**Issue by PhilipSpechler** [MatthieuStigler/RDDtools#5]
Hello, I have two questions about including covariates in my RDD model:

For context, I have a [5280 x 4] dataframe ('my_df') containing an x-variable ('distance'), y-variable ('IQ'), and 2-covariates ('age', 'sex') for n=5,280 subjects. The idea is to test for a discontinuity in IQ based on distance to a time-zone boundary (social jet lag phenomenon), while accounting for age and sex. 

**Q1: How do I properly specify those two covariates?** 

I am using 'rdd_data' to declare an RDD object:
IQ_RDD <- rdd_data(y=IQ, x=distance, covar=c('age', 'sex'), cutpoint=0, data=my_df)

But this seems to double the row-length of the new "IQ_RDD" dataframe [10560 x 3]. This approach is clearly wrong, as I see IQ_RDD$`c("age","sex")`. I note that this issue persists even when setting covariates with and without single and double apostrophes (covar=c("age","sex"); covar=c(age,sex), etc.)  

The only approach that seems to be accurate is when I set covars by directly indexing "my_df", like this:

IQ_RDD <- rdd_data(y=IQ, x=distance, covar=my_df[ , c('age', 'sex')], cutpoint=0, data=my_df).

If this is correct, then please make this explicit in the help file. 

Side note, things work as expected if I just specify one covariate (for example, covar=age)

**Q2: How do I properly include those covariates when fitting a linear RDD model?**

IQ_RDD_lm <- rdd_reg_lm(IQ_RDD, order=1, covar.opt = 'include')

And getting this error:
"Error: $ operator is invalid for atomic vectors"

I still get this error when I set my rdd_data object with only one covariate. 

The help file says "covariates    Formula to include covariates". I want them to be modeled in an additive fashion, typical of a multiple regression model (Beta-age + Beta-sex), but it's unclear how to make this work. Any guidance would be helpful. 

Thanks!!!

**Comment by MatthieuStigler** [comment]
Hi Philip!

Thanks for the report. Note that I've opened both issues on the repo we use for this package. As a quick summary:

- the first issue was a bug indeed, I had to go back to the intricacies of quotation in base R
- the second point is a mis-use of the argument, it should be a list instead. But now there is a clearer warning.

Updated code is available https://github.com/bquast/rddtools, and will be pushed at some point to CRAN. Let us know if you have other concerns.

And as usual, we are always thankful if you can acknowledge the use of the package in any work, use `citation("rddtools")`.
